### ISSUE TITLE
undefined symbol: glXGetCurrentContext

### ISSUE THREAD

**Issue by AngelGamer29JA** [deno-windowing/dwm#22]
deno: symbol lookup error: /home/angel/.cache/deno/plug/https/github.com/6124705c167a5007bfab218a8e66994369ecb4e10c7f44d4dbf2c97b8d05084b.so: undefined symbol: glXGetCurrentContext

```ts
import {
  mainloop,
  WindowCanvas,
} from "https://deno.land/x/dwm@0.3.3/ext/canvas.ts";

const canvas = new WindowCanvas({
  title: "Skia Canvas",
  width: 800,
  height: 600,
  resizable: true,
});

canvas.onDraw = (ctx) => {
  ctx.fillStyle = "black";
  ctx.fillRect(0, 0, ctx.canvas.width, ctx.canvas.height);
  ctx.fillStyle = "white";
  ctx.font = "30px Arial";
  ctx.textBaseline = "top";
  ctx.fillText("Hello World", 10, 10);
};

await mainloop(() => {
  canvas.draw();
});`

**Comment by DjDeveloperr** [comment]
Should be fixed in 7cf4070b

**Comment by rylydou** [comment]
I am also having the same issue.

**Comment by chances** [comment]
> Should be fixed in [7cf4070](https://github.com/deno-windowing/dwm/commit/7cf4070b20d1ccaabe9a9b0a0000ab7aa29b9c4b)

This issue is not fixed when I target `0.3.6`. Has there been any newer fixes made to resolve this issue?

**Comment by chances** [comment]
I've opened https://github.com/deno-windowing/dwm/pull/34 to address this issue.

**Comment by iluha168** [comment]
I am also having the same issue. I have narrowed it down to this call:
```ts
import { createCanvas } from "jsr:@gfx/canvas@0.5.8"

createCanvas(100, 100, true)
```
The error is only thrown when ``gpu`` flag is ``true``.
```
deno: symbol lookup error: ~/.cache/deno/plug/https/github.com/6cd7acf911cb7a3c6b878f4cbcd006ea0e219ed16cb07c0bc41d4d795e30f800.so: undefined symbol: glXGetCurrentContext
```

``uname -a``:
```
Linux <censored> 6.9.12-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.9.12-1 (2024-07-27) x86_64 GNU/Linux
```
